version: 2 

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6.8
        environment:
          SECRET_KEY: $SECRET_KEY
          SQL_ENGINE: $SQL_ENGINE
          SQL_DATABASE: $SQL_DATABASE
          SQL_USER: $SQL_USER
          SQL_PASSWORD: $SQL_PASSWORD
          SQL_HOST: $SQL_HOST
          SQL_PORT: $SQL_PORT
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache: # cache Python dependencies
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run --source='.' manage.py test
            coverage report
            coverage html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov