---
- name: Create a virtualenv directory
  file:
    path: "{{ venv_dir }}"
    state: directory


- name: Install setup tools
  pip:
    name: setuptools
    executable: pip3

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
  become: yes
  become_user: root

- name: Install dependencies
  pip:
    requirements: "{{ app_dir }}/requirements/production.txt"
    virtualenv: "{{ venv_dir }}"
    virtualenv_python: python3.6

<<<<<<< HEAD
- name: Create the environment variables bash file
=======
- name: Create the env bash script
>>>>>>> 94714aa... Added publish to circleCI
  template:
    src: env.j2
    dest: "{{ app_dir }}/env.sh"
  become: yes
  become_user: "{{ deployer_user }}"

- name: Make the script executable
  file:
    dest: "{{ app_dir }}/env.sh"
    mode: a+x
<<<<<<< HEAD
  become: yes
=======
  become: yes

# - name: Execute the script
#   shell: source ./env.sh 
#   become: yes
#   become_user: root
#   args:
#     chdir: /home/ubuntu/muchogo/portfolio
>>>>>>> 94714aa... Added publish to circleCI
