---
- name: Install nginx
  apt:
   name: nginx
   state: latest
  become: yes

- name: Write nginx conf file
  template:
   src: portfolio.conf
   dest: /etc/nginx/conf.d/portfolio.conf
  become: yes
  notify:
    - restart nginx