---
- name: deploy directory
  file:
    path: "{{ deploy_dir }}"
    state: directory
  become: yes
  become_user: "{{ deployer_user }}"

- name: Gunicorn_start script
  template:
    src: gunicorn_start
    dest: "{{ deploy_dir }}/gunicorn_start"
  become: yes

- name: Make the script executable
  file:
    dest: "{{ deploy_dir }}/gunicorn_start"
    mode: a+x
  become: yes